"""Local browser interface. Start with python -m pyutloc.gui, then open localhost."""
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
from pathlib import Path
import json
from .core import normalize
HTML='''<!doctype html><html lang="en"><meta charset="utf-8"><title>PyUTLoc coordinate normalization</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f5f6f7;color:#1c2e3b;font:15px Arial,sans-serif}main{max-width:1120px;margin:38px auto}h1{font-size:29px;margin:0 0 8px}p{color:#60717d;line-height:1.5}header{border-bottom:1px solid #d4dde2;padding-bottom:20px;margin-bottom:26px}.content{display:grid;grid-template-columns:1fr 1.35fr;gap:32px}h2{font-size:17px;margin:0 0 14px}label{display:block;margin:14px 0 7px;font-size:13px;font-weight:bold}textarea,input,select{border:1px solid #bdcbd3;background:white;border-radius:3px;padding:10px;font:14px Consolas,monospace;width:100%}textarea{height:182px;resize:vertical;line-height:1.8}button{background:#176985;color:white;border:0;border-radius:3px;padding:12px 22px;margin:20px 10px 18px 0;cursor:pointer}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}table{border-collapse:collapse;width:100%;background:white;font-size:13px}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid #dce4e9}th{background:#e9eff3}td.good{color:#14725f}td.bad{color:#a84c30}code{font:13px Consolas,monospace}#map{background:white;border:1px solid #dce4e9;margin-top:20px;width:100%;height:216px}.note{font-size:12px;color:#687985}#message{margin:0 0 15px;font-weight:bold}footer{margin-top:24px;border-top:1px solid #d4dde2;padding-top:16px;font-size:12px;color:#60717d}</style>
<main><header><h1>PyUTLoc</h1><p>Normalize coordinate representations with explicit reference systems and validation.</p></header><div class="content"><section><h2>Input coordinates</h2><textarea id="input">39.9 116.4
N 39° 54′ 0″ E 116° 24′ 0″
34.12S 118.43E
91.0 20.0</textarea><div class="two"><div><label>Source coordinate reference system</label><input id="crs" value="EPSG:4326"></div><div><label>Coordinate order</label><select id="order"><option value="latlon">Latitude, longitude</option><option value="lonlat">Longitude, latitude</option><option value="xy">Easting, northing</option><option value="yx">Northing, easting</option></select></div></div><div class="two"><div><label>Format convention</label><select id="hint"><option value="">Automatic detection</option><option>MGRS</option><option>USNG</option><option>GEOHASH</option></select></div><div><label>UTM letter convention</label><select id="utm"><option value="">Unspecified</option><option value="band">Latitude band</option><option value="hemisphere">Hemisphere</option></select></div></div><button onclick="run()">Normalize coordinates</button><p class="note">Each line is one coordinate. The source CRS is supplied by the user. Ambiguous and invalid inputs retain their diagnostic status.</p></section><section><h2>WGS84 results</h2><div id="message">Ready</div><table><thead><tr><th>Row</th><th>Format</th><th>Latitude</th><th>Longitude</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table><svg id="map" viewBox="0 0 600 216"></svg><p class="note">Coordinate preview in longitude and latitude. Grid spacing is 60° longitude and 30° latitude.</p><button onclick="download()">Export JSON results</button></section></div><footer>Local interface · PyUTLoc 2.0.0rc1 · Coordinates stay in this local session</footer></main>
<script>let results=[];const $=x=>document.getElementById(x);async function run(){let r=await fetch('/normalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('input').value,source_crs:$('crs').value,axis_order:$('order').value,format_hint:$('hint').value||null,utm_convention:$('utm').value||null})});results=await r.json();$('rows').replaceChildren();results.forEach((v,i)=>{let tr=document.createElement('tr');[i+1,v.format||'—',v.latitude?.toFixed(6)||'—',v.longitude?.toFixed(6)||'—',v.status].forEach((t,j)=>{let td=document.createElement('td');td.textContent=t;if(j===4){td.className=v.status==='ok'?'good':'bad';td.title=v.reason||''}tr.append(td)});$('rows').append(tr)});$('message').textContent=results.filter(x=>x.status==='ok').length+' valid / '+results.length+' records';let s='';for(let x=0;x<=600;x+=100)s+=`<line x1="${x}" y1="0" x2="${x}" y2="216" stroke="#e0e7eb"/>`;for(let y=0;y<=216;y+=36)s+=`<line x1="0" y1="${y}" x2="600" y2="${y}" stroke="#e0e7eb"/>`;s+='<line x1="0" y1="108" x2="600" y2="108" stroke="#aab9c3"/>';results.forEach((v,i)=>{if(v.status==='ok')s+=`<circle cx="${(v.longitude+180)/360*600}" cy="${(90-v.latitude)/180*216}" r="5" fill="#187894"/><text x="${(v.longitude+180)/360*600+8}" y="${(90-v.latitude)/180*216-6}" fill="#24475b" font-size="12">${i+1}</text>`});$('map').innerHTML=s}function download(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(results,null,2)],{type:'application/json'}));a.download='pyutloc_results.json';a.click()}run();</script></html>'''
class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200);self.send_header('Content-Type','text/html; charset=utf-8');self.end_headers();self.wfile.write(HTML.encode())
    def do_POST(self):
        size=int(self.headers.get('Content-Length',0))
        if self.path!='/normalize' or size>1000000:self.send_error(400);return
        try:
            d=json.loads(self.rfile.read(size));texts=d.pop('text').splitlines();texts=[s for s in texts if s.strip()]
            if len(texts)>1000:raise ValueError('maximum 1000 rows per local request')
            rows=[normalize(t,**d).to_dict() for t in texts]
            self.send_response(200);self.send_header('Content-Type','application/json');self.end_headers();self.wfile.write(json.dumps(rows).encode())
        except Exception:self.send_error(400,'Invalid input')
    def log_message(self,*args):pass
def main():
    print('Open http://127.0.0.1:8766 in your browser. Press Ctrl+C to stop.',flush=True)
    ThreadingHTTPServer(('127.0.0.1',8766),Handler).serve_forever()
if __name__=='__main__':main()
